repos:
  - repo: local
    hooks:
      - id: validate-taxonomy
        name: Validate project taxonomy
        entry: python3 scripts/validate_taxonomy.py
        language: system
        pass_filenames: false

